"""
Django settings for learning_log project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
# -*- coding: UTF-8 -*-
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#项目路径
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#安全密钥
SECRET_KEY = ')m^_yck=xrk#v)*y#i17eioj=l#pn%^&6#arxh#8ogyfzcabzx'

# SECURITY WARNING: don't run with debug turned on in production!
#是否开始debug调试
DEBUG = True

#允许访问的主机
ALLOWED_HOSTS = []


# Application definition
#加载的app
INSTALLED_APPS = [
    'django.contrib.admin',#管理后台
    'django.contrib.auth',#验证应用
    'django.contrib.contenttypes',#内容类型
    'django.contrib.sessions',#回话支持
    'django.contrib.messages',#消息传递
    'django.contrib.staticfiles',#静态文件应用
    #以上为django自带的应用
    #新建的应用在下面添加
    #例如   'myapp'，
    'testModel',
]

#中间件模块
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#指定URL列表文件
ROOT_URLCONF = 'learning_log.urls'

#加载网页模板的路径
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#WSGI的配置文件路径
WSGI_APPLICATION = 'learning_log.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
#数据库配置
DATABASES = {
    #'default': {
    #   'ENGINE': 'django.db.backends.sqlite3',
    #   'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    #}
    #mysql链接如下
    'default':{
        'ENGINE':'django.db.backends.mysql',
        'NAME':'library_system',
        'USER':'root',
        'PASSWORD':'123456',
        'HOST':'112.124.13.127',
        'PORT':'3306',
    }
               #  需要在__init__.py文件添加import pymysql
               #                             pymysql.install_as_MySQLdb()
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
#密码验证相关
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
#语言设置
LANGUAGE_CODE = 'en-us'
#时区配置
TIME_ZONE = 'UTC'
#i18n字符集支持
USE_I18N = True

USE_L10N = True

#是否使用timezone
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
#静态文件URL
STATIC_URL = '/static/'
