# Generated by Django 2.2.7 on 2019-11-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestmodelUserinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('group', models.CharField(max_length=4)),
                ('idpassword', models.CharField(max_length=19, unique=True)),
            ],
            options={
                'db_table': 'testModel_userinfo',
                'managed': False,
            },
        ),
    ]
